openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
  description: Secure API for managing user tasks with CRUD operations and authentication

paths:
  /api/{user_id}/tasks:
    get:
      summary: List all tasks for a user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user whose tasks to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Successful response with list of tasks
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/TaskResponse'
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User attempting to access another user's tasks
      security:
        - bearerAuth: []

    post:
      summary: Create a new task
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user creating the task
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '400':
          description: Bad request - Invalid input data
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User attempting to create task for another user
      security:
        - bearerAuth: []

  /api/{user_id}/tasks/{id}:
    get:
      summary: Get a specific task
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: The ID of the task
          schema:
            type: integer
      responses:
        '200':
          description: Successful response with task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User attempting to access another user's task
        '404':
          description: Not found - Task does not exist
      security:
        - bearerAuth: []

    put:
      summary: Update a task
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: The ID of the task
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '400':
          description: Bad request - Invalid input data
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User attempting to update another user's task
        '404':
          description: Not found - Task does not exist
      security:
        - bearerAuth: []

    delete:
      summary: Delete a task
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: The ID of the task
          schema:
            type: integer
      responses:
        '200':
          description: Task deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Task deleted successfully"
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User attempting to delete another user's task
        '404':
          description: Not found - Task does not exist
      security:
        - bearerAuth: []

  /api/{user_id}/tasks/{id}/complete:
    patch:
      summary: Toggle task completion status
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: The ID of the task
          schema:
            type: integer
      responses:
        '200':
          description: Task completion status toggled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User attempting to update another user's task
        '404':
          description: Not found - Task does not exist
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    TaskBase:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
          example: "Buy groceries"
        description:
          type: string
          maxLength: 1000
          example: "Need to buy milk, bread, and eggs"
      required:
        - title

    TaskCreate:
      allOf:
        - $ref: '#/components/schemas/TaskBase'

    TaskUpdate:
      allOf:
        - $ref: '#/components/schemas/TaskBase'
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
          example: "Buy groceries"
        description:
          type: string
          maxLength: 1000
          example: "Need to buy milk, bread, and eggs"
        completed:
          type: boolean
          example: false

    TaskResponse:
      allOf:
        - $ref: '#/components/schemas/TaskBase'
      properties:
        id:
          type: integer
          example: 1
        completed:
          type: boolean
          example: false
        user_id:
          type: string
          example: "user_abc123"
        created_at:
          type: string
          format: date-time
          example: "2023-01-01T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2023-01-01T10:00:00Z"
      required:
        - id
        - title
        - completed
        - user_id
        - created_at
        - updated_at